version: '3.1'
services:
  blink-unity:
    image: "${IMAGE_NAME}"
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s


  
